#!/bin/bash

vssettingspath=/mnt/c/Users/Manik/AppData/Roaming/Code/User/settings.json
windowsterminalpath=/mnt/c/Users/Manik/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
rainmeterpath=/mnt/c/Users/Manik/Drive/Documents/Rainmeter/Skins/

echo "Copying Visual Studio Code settings"
cp $vssettingspath /home/manik/vs-settings.json

echo "Copying Windows Terminal Preview settings"
cp $windowsterminalpath /home/manik/wtp-settings.json

echo "Copy rainmeter skins"
cp $rainmeterpath -r /home/manik/widgets
