install :	
		@echo "installing all scripts"

		@echo "installing syncnas"
		@cp common/syncnas.sh /usr/local/bin/

		@echo "installing updatedots"
		@cp common/updatedots.sh /usr/local/bin/

		@echo "installing common_utils.sh"
		@cp common/common_utils.sh /usr/local/bin

		
uninstall :
		@echo "uninstalling all scripts"
		@rm -r /usr/local/bin/syncnas.sh
		@rm -r /usr/local/bin/updatedots.sh
		@rm -r /usr/local/bin/copywinsettings.sh
