install :	
		@echo "installing all scripts"

		@echo "installing syncnas"
		@cp syncnas /usr/local/bin/

		@echo "installing updatedots"
		@cp updatedots /usr/local/bin/

		@echo "installing common_utils.sh"
		@cp common_utils.sh /usr/local/bin
		
		@echo "installing copywinsettings"
		@cp copywinsettings /usr/local/bin

		@echo "installing info.sh"
		@cp info.sh /usr/local/bin
		
uninstall :
		@echo "uninstalling all scripts"
		@rm -r /usr/local/bin/syncnas
		@rm -r /usr/local/bin/updatedots	
		@rm -r /usr/local/bin/info.sh
		@rm -r /usr/local/bin/copywinsettings
