#!/bin/bash
HOST='squishypi.lan'
PATHTODOC='/home/manik/NAS/Documents'
PATHTOPROJ='/home/manik/NAS/Projects'
PATHTOPICS='/home/manik/NAS/Photos/Pictures'
#Checking if connected to the NAS
if ping -q -c 1 -W 1 $HOST >/dev/null; 
then	
	echo "$HOST online, checking if mounted"
	
	#Checking if the path to NAS exists, i.e. if it's mounted
	if [ -d 'home/manik/NAS/Downloads' ] 
	then
		    echo "NAS mounted" 
	else
		    echo "Error: NAS not mounted"
		    echo "Attempting mount"
		    sudo mount -a
		    if [ -d $PATHTODOC ]
		    then
		    	    echo "Mounted"
		    fi
	fi
	
	echo "Running rsync"
	
	if [ -d $PATHTODOC ]
	then
		echo "Syncing Documents"
		rsync -rtvu --delete "/home/manik/Manik/Drive/Documents/" $PATHTODOC
	else
		echo "Documents folder not found on the NAS"
	fi
	
	if [ -d $PATHTOPROJ ]
	then
		echo "Syncing Projects"
		rsync -rtvu --delete "/home/manik/Manik/Projects/" $PATHTOPROJ
	else
		echo "Projects folder not found on the NAS"
	fi

	if [ -d $PATHTOPICS ]
	then
		echo "Syncing Photos"
		rsync -rtvu --delete "/home/manik/Manik/Pictures/" $PATHTOPICS
	else
		echo "Picture folder not found on the NAS"
	fi
	
else
	#Quitting if not host not found online
	echo "$HOST not Found, can't sync. Quitting."
fi

